#!/usr/bin/env -S npx tsx
// Round 4 (issue #820, tray-repo prerequisites) — the round-1 plan's own
// PR2 line item ("ship the filter table as a machine-readable fixture the
// separate repo consumes") was never delivered: SSH_AGENT_REQUEST_TYPE_VECTORS
// (src/services/ssh-agent-filter.ts) shipped as a TypeScript-only export for
// two full rounds. This script is that fixture's generator.
//
// A `.ts` file, not `.mjs` like every other script here (run via `tsx`, an
// existing devDependency) — it needs to import the real, typed
// SSH_AGENT_REQUEST_TYPE_VECTORS table from src/services/, and the `.mjs`
// CLI tree's own "zero-dependency, node: builtins only" constraint doesn't
// apply to build-time tooling like this, only to what ships inside the SEA
// (see src/cli/ssh-agent-bridge-mux.mjs's own header comment on why THAT
// tree can't import TypeScript at all).
//
// Two modes, mirroring check-env-docs.mjs/check-briefing-sync.mjs's own
// dual "regenerate" / "--check" shape:
//   node/tsx scripts/generate-ssh-agent-filter-vectors.ts          — writes
//   node/tsx scripts/generate-ssh-agent-filter-vectors.ts --check  — exits
//     nonzero if the checked-in fixture doesn't match what this would
//     generate right now. Wired into `npm run lint` so the fixture can't
//     silently drift from the TS table the way it already did once.
import { writeFileSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  SSH_AGENT_REQUEST_TYPE_VECTORS,
  SSH_AGENT_FAILURE,
  SSH_AGENT_FAILURE_FRAME,
  LENGTH_PREFIX_BYTES,
  MAX_FRAME_BYTES,
} from "../src/services/ssh-agent-filter.js";
import { CHANNEL_WINDOW_BYTES } from "../src/services/ssh-agent-mux.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// Overridable so tests can point this at a tmpdir fixture instead of the
// real, tracked JSON file — same convention as check-briefing-sync.mjs's
// own BRIEFING_SYNC_ROOT (see that script's comment). Every real invocation
// (`npm run lint`, `npm run generate:ssh-agent-filter-vectors`) leaves this
// unset and gets the real repo path.
const FIXTURE_PATH =
  process.env.SSH_AGENT_FILTER_VECTORS_FIXTURE_PATH ??
  path.join(root, "test/fixtures/ssh-agent-filter-vectors.json");

export interface SshAgentFilterFixture {
  description: string;
  generatedFrom: string;
  wireFormat: {
    lengthPrefixBytes: number;
    lengthPrefixEndianness: "big";
    maxFrameBytes: number;
  };
  /** Unlisted types are blocked, not passed through — classify()'s own
   * default-deny behavior (ssh-agent-filter.ts). A reimplementer who only
   * ports the `vectors` array below and treats anything absent from it as
   * ALLOWED would get this exactly backwards. */
  defaultAllowed: boolean;
  /** The real agent's own replies (identities answer, sign response,
   * success/failure) are always relayed unfiltered — this filter only ever
   * classifies REQUESTS. Stated explicitly so an importer doesn't filter
   * both directions by mistake. */
  replyDirectionFiltered: boolean;
  sshAgentFailure: {
    type: number;
    /** The exact bytes of the synthesized rejection reply, as hex — always
     * this same 5-byte frame regardless of which request it's replying to. */
    frameHex: string;
  };
  /** Issue #1059 — constants that come from this repo's own mux frame
   * format (ssh-agent-mux.ts's CHANNEL_WINDOW_BYTES), NOT the SSH agent
   * wire protocol `wireFormat` describes. Pinned here so the same hand-
   * edit drift risk the filter twins face has a single source of truth
   * this script's --check guard catches. */
  muxTransport: {
    channelWindowBytes: number;
  };
  vectors: { type: number; name: string; allowed: boolean }[];
  /** Behaviors that aren't representable in the {type,name,allowed} shape
   * alone — each one already has a discriminating test in
   * test/services/ssh-agent-filter.test.ts; this is that coverage,
   * described for a reimplementer rather than left implicit. Self-review,
   * PR #913: unlike `vectors` above, this prose is hand-written, not
   * derived from source — the `--check` drift guard can't catch it going
   * stale if `classify()`/`feed()`'s actual behavior ever changes. Update
   * it by hand alongside any such change. */
  edgeCases: { name: string; description: string }[];
}

export function buildFixture(): SshAgentFilterFixture {
  return {
    description:
      "The SSH agent wire-protocol sign-only filter's conformance table — " +
      "every known SSH_AGENTC_* request type mapped to its allow/block " +
      "decision. Generated, not hand-maintained; do not edit this file " +
      "directly, edit src/services/ssh-agent-filter.ts and regenerate " +
      "(npm run generate:ssh-agent-filter-vectors).",
    generatedFrom: "src/services/ssh-agent-filter.ts",
    wireFormat: {
      lengthPrefixBytes: LENGTH_PREFIX_BYTES,
      lengthPrefixEndianness: "big",
      maxFrameBytes: MAX_FRAME_BYTES,
    },
    defaultAllowed: false,
    replyDirectionFiltered: false,
    sshAgentFailure: {
      type: SSH_AGENT_FAILURE,
      frameHex: SSH_AGENT_FAILURE_FRAME.toString("hex"),
    },
    /** Issue #1059 — the mux twins' CHANNEL_WINDOW_BYTES, extracted here so
     * a hand-edit to either twin's source that drifts from the other fails
     * this script's --check guard, the same way a hand-edit to
     * SSH_AGENT_REQUEST_TYPE_VECTORS already does. NOT under wireFormat:
     * wireFormat describes the SSH agent protocol this filter parses, while
     * channelWindowBytes describes this repo's own mux frame format
     * (different protocol, see ssh-agent-mux.ts's own header comment) — the
     * two deliberately aren't conflated. */
    muxTransport: {
      channelWindowBytes: CHANNEL_WINDOW_BYTES,
    },
    vectors: SSH_AGENT_REQUEST_TYPE_VECTORS.map((v) => ({
      type: v.type,
      name: v.name,
      allowed: v.allowed,
    })),
    edgeCases: [
      {
        name: "zero-length-body",
        description:
          "A frame with body length 0 (no type byte to classify) is BLOCKED, not thrown — " +
          "treated as fully-parsed, bounded input, the same as any other frame absent from " +
          "the allowlist. Only an untrustworthy LENGTH prefix (see oversized-declared-length " +
          "below) is fatal.",
      },
      {
        name: "oversized-declared-length",
        description:
          "A declared body length exceeding maxFrameBytes is FATAL — throw / tear down the " +
          "connection, not silently block or cap. The length prefix itself can't be trusted " +
          "at that point, so it's not safe to keep parsing the stream at all.",
      },
      {
        name: "allowed-frames-forwarded-unmodified",
        description:
          "An allowed frame is forwarded byte-for-byte to the real agent socket, including " +
          "its own length prefix — never re-encoded, re-framed, or otherwise touched.",
      },
      {
        name: "rejected-length-tracking",
        description:
          "Each blocked frame's ORIGINAL byte length (length prefix + body) must be tracked " +
          "separately from the synthesized failure reply's own fixed 5-byte size — a relay " +
          "acknowledging flow-control credit for the request needs the real size, not the " +
          "reply's.",
      },
    ],
  };
}

function main(): void {
  const fixture = buildFixture();
  const rendered = `${JSON.stringify(fixture, null, 2)}\n`;

  if (process.argv.includes("--check")) {
    let onDisk: string | null;
    try {
      onDisk = readFileSync(FIXTURE_PATH, "utf8");
    } catch {
      onDisk = null; // doesn't exist yet — same "out of date" message covers this case too
    }
    if (onDisk !== rendered) {
      process.stderr.write(
        `test/fixtures/ssh-agent-filter-vectors.json is out of date with ` +
          `src/services/ssh-agent-filter.ts — run 'npm run generate:ssh-agent-filter-vectors' ` +
          `and commit the result.\n`,
      );
      process.exit(1);
    }
    process.stdout.write("OK — ssh-agent-filter-vectors.json matches the live TS table.\n");
    return;
  }

  writeFileSync(FIXTURE_PATH, rendered);
  process.stdout.write(`wrote ${path.relative(root, FIXTURE_PATH)}\n`);
}

// Guarded, not a bare `main()` call at module scope: test/scripts/generate-
// ssh-agent-filter-vectors.test.ts imports `buildFixture` directly (to
// assert it matches the live TS table without shelling out) — an
// unconditional `main()` here would make that plain import ALSO overwrite
// (or --check, or exit the process) as a side effect of merely importing
// the module, which is exactly the kind of surprising behavior a reusable
// function/CLI-entry-point split (core.mjs's own convention) exists to
// avoid.
if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1] ?? "")) {
  main();
}
